### ISSUE TITLE
how to "preventDefault" event such as choose text when dragging

### ISSUE THREAD

**Issue by anewzsw** [jbaysolutions/vue-grid-layout#115]

**Comment by SergeyKhval** [comment]
You can use `user-select: none` for this

**Comment by shichuanpo** [comment]
I have the same enquiries too

**Comment by llwinner** [comment]
I have the same question too.

**Comment by llwinner** [comment]
I found the solution to the problem.
```
    .vue-grid-item {
        transition: all 200ms ease;
        transition-property: left, top, right;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        -o-user-select: none;
        user-select: none;

        /* add right for rtl */
    }
```
I tested it, and now everything is well.

**Comment by acorbel** [comment]
Based on @SergeyKhval answer, I listen the move and resize events with the following function:
```js
this.onDrag = true;
if (!this.dragTimer) {
   this.dragTimer = window.setTimeout(() => { // clear in beforeDestroy if set
       this.onDrag = false;
       this.dragTimer = null;
}, 500);
```

and I have a class attached to the onDrag property:
```css
  .disable-selection {
    -webkit-user-select: none;  /* Chrome all / Safari all */
    -moz-user-select: none;     /* Firefox all */
    -ms-user-select: none;      /* IE 10+ */
    user-select: none;          /* Likely future */
  }
```

It is not very elegant but it works fine.

However, it does not work for IE 9- and Opera mini (see: [caniuse](https://caniuse.com/#search=user-select))
