### ISSUE TITLE
Option to disable animations

### ISSUE THREAD

**Issue by lucas-bremond** [jbaysolutions/vue-grid-layout#158]
Terrific plug-in!

Is there a way to disable animations?
Because it's conflicting with my own stuff...

Thanks!

**Comment by ikbelkirasan** [comment]
I think you can disable the css transitions like this:
```css
.vue-grid-item {
  /* transition: all 200ms ease; */
  transition: none;
}

.vue-grid-layout {
  /* transition: height 200ms ease; */
  transition: none;
}

```
