### ISSUE TITLE
Document how to "maximize" a GridItem...

### ISSUE THREAD

**Issue by pmorch** [jbaysolutions/vue-grid-layout#333]
When using a grid layout, sometimes I want to maximize a certain GridItem (e.g. temporarily). The vue-grid-layout API doesn't provide a way to do that. But it can be done. Here is a working [codesandbox](https://codesandbox.io/s/vue-grid-layout-maximize-widget-0ty14) demo.

Kibana, the Elastic Search GUI can do it. It uses [React-Grid-Layout](https://github.com/STRML/react-grid-layout) that heavily inspired this project, and the approach Kibana uses with react-grid-layout works fine with vue-grid-layout as well. I took a look at how Kibana does it, by looking at their [demo](https://demo.elastic.co/app/kibana#/dashboard/f110f010-11fc-11e8-8c94-a3d8d0cfd62b) (in case that link changes, it was a link to the "[Azure Monitor] Overview" dashboard - but look at any kibana dashboard to see what I mean):

![image](https://user-images.githubusercontent.com/159292/60162848-a6595000-97fa-11e9-993b-3389c11cdad5.png)

The heart of the approach is to notice that while (vue|react)-grid-layout is in control, vue-grid-layout sets CSS directly on each of the .vue-grid-item elements like this:

```css
element {
	transform: translate3d(218px, 10px, 0px);
	width: 198px;
	height: 150px;
	position: absolute;
}
```

What we do is set a `maximizedID` state variable. If it is set, then all the non-maximized grid-items get a class that sets `display:none` to hide them, and the maximized element gets this CSS class:

```css
.vue-grid-item.maximized {
  transform: inherit !important;
  height: 100% !important;
  width: 100% !important;
}
```
Which overrides the CSS attributes set on the elements themselves, resulting in a full-screen GridItem (or 100% height/width of whatever container it is in). Also `is-draggable` and `is-resizable` are false when maximized.

Ideally I would've liked this documented. But otherwise fell free just to close this issue. Now the next guy who comes along and searches for "maximized" or "full-screen" will find now find this issue as a starting point.
