### ISSUE TITLE
No initial transitions

### ISSUE THREAD

**Issue by Aljodomo** [jbaysolutions/vue-grid-layout#473]
**Describe the solution you'd like**
When loading the grid, every item is transitioning from the top left to its real position. It would be perfect if the elements appear in their final position.

**Describe alternatives you've considered**
I tried to hide all items until the transitions are finished but that is a horrible solution.

Any tips for me to implement that? I am new to vue and js development but I am trying my best :)

**Comment by halfpastfouram** [comment]
You can cancel the transitions by overriding these CSS rules:

```scss
.vue-grid-item {
  -webkit-transition: unset !important;
  transition: unset !important;;
  -webkit-transition-property: unset !important;
  transition-property: unset !important;
}
```
