### ISSUE TITLE
Is there anyway to stop the content(text) leak out of the widget

### ISSUE THREAD

**Issue by fuwei007** [jbaysolutions/vue-grid-layout#775]
If you go to the demo page 
https://jbaysolutions.github.io/vue-grid-layout/
resize the second widget. You will see

![image](https://github.com/jbaysolutions/vue-grid-layout/assets/4459271/1fe40496-51bf-446a-98cb-ee6ff5cf64ed)

is there any property we could set to stop the content inside of box get out.

Thanks

Frank

**Comment by gwinnem** [comment]
Hi @fuwei007 
This is a css issue.
In my version I have the same issue when I add the title using:
```html
  <span class="text">
    {{ itemTitle(item) }}
  </span>
```

And my text css class is:
```css
.text {
  bottom: 0;
  font-size: 24px;
  height: 100%;
  left: 0;
  margin: auto;
  position: absolute;
  right: 0;
  text-align: center;
  top: 0;
  width: 100%;
}
```

So add some css magic to fix your issue.

Regards

[Geirr Winnem](https://github.com/gwinnem/vue-responsive-grid-layout)

Link is to my Vue 3 version completely rewrite of this one here.
